In [3]:
#Libraries used in the assignment
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

file = 'ux_data.xlsx'
dataset = pd.read_excel(file, "Dataset")

dataset

   Age  Height       OS
0   23     156      IOS
1   26     183  Android
2   72     175      IOS
3   47     192  Android
4   13     167  Android

In [15]:
df = pd.DataFrame(dataset)
df.describe(include='all')

              Age      Height       OS
count    5.000000    5.000000        5
unique        NaN         NaN        2
top           NaN         NaN  Android
freq          NaN         NaN        3
mean    36.200000  174.600000      NaN
std     23.530831   13.939153      NaN
min     13.000000  156.000000      NaN
25%     23.000000  167.000000      NaN
50%     26.000000  175.000000      NaN
75%     47.000000  183.000000      NaN
max     72.000000  192.000000      NaN

In [16]:
df.size

15

I used an imaginary recruitment method to maximize speed of data sampling.

There is a potential bias in the method by the fact that the people are fictional, and therefore created in my own head. This means that the data is created from my own cognitive stereotypes of the fictional people, and therefore doesn't clearly represent any potential group. The data should not be taken serious in any kind of context, and nothing can be concluded from it.